### ISSUE TITLE
Community Contribution Guidelines

### ISSUE THREAD

**Issue by wincowgerDEV** [U-Alberta/ADaPT-ML#2]
Thanks for the invitation as a reviewer of this software. I am currently going through the JOSS checklist and am flagging one issue here that I cannot find "Community guidelines." JOSS would like you to have guidelines listed that clearly indicate how third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support can do so. Following your documentation, I found community guidelines at [HERE](https://github.com/U-Alberta/ADaPT-ML/blob/main/usage.md ) which primarily are a wishlist for new updates to the tool. I think there should be additional documentation for the three community use cases listed by JOSS that I indicated above.

**Comment by nulberry** [comment]
Thank you for bringing this to my attention. In commit 9412302be59a109bfbd5e2a230a83ca0fe45f710, I added a note at the end of the contribution guidelines requesting that people open an issue if they have an idea about adding new or improving existing features, and I have also added a new section for reporting problems and seeking support, where I also encourage users to open an issue if they need help. Please let me know what you think of these changes.

**Comment by wincowgerDEV** [comment]
Looking better, just added one small comment.
