### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by wincowgerDEV** [U-Alberta/ADaPT-ML#3]
JOSS would like to see Automated tests for the software. I see that there are manual tests for the software where a user can work through an example, but I am not sure if there are automated tests that you have also set up to ensure the software is behaving as expected?

**Comment by nulberry** [comment]
Hi! I have automated tests set up through the GitHub Actions for this repository. These workflows use the same testing scripts and procedures as the manual tests. if you would like to view the workflow files, they are [here](https://github.com/U-Alberta/ADaPT-ML/tree/main/.github/workflows).

**Comment by wincowgerDEV** [comment]
> Hi! I have automated tests set up through the GitHub Actions for this repository. These workflows use the same testing scripts and procedures as the manual tests. if you would like to view the workflow files, they are [here](https://github.com/U-Alberta/ADaPT-ML/tree/main/.github/workflows).

Thanks for pointing that out, looks great. I will close this issue now.
