### ISSUE TITLE
Add mention of other Open Source MLOps projects in manuscript

### ISSUE THREAD

**Issue by wincowgerDEV** [U-Alberta/ADaPT-ML#5]
The related projects in the paper.md file mention a project which used this tool and another one which is a proprietary MLOps software. As a reader, I want to know, are there other open source MLOps software out there that do a similar job to this tool? If not, that should be stated somewhere in the manuscript.

**Comment by wincowgerDEV** [comment]
Also, I think it is important to mention the differences between this software and the Snorkel Flow software if that is the main similar software out there.

**Comment by nulberry** [comment]
In 1dd2aaae11c68fd637edcfad8568df75b235b7bd, I added a short comparison between ADaPT-ML and Snorkel Flow (without having access to the software, I decided that the most obvious difference was the Snorkel Flow UI that allows for super easy labelling function and end model creation and evaluation... my goal is that one day ADaPT-ML will have a UI to simplify things for users!). I also noted the differences between ADaPT-ML and two other MLOps platforms, Neu.ro and MLRun.

**Comment by wincowgerDEV** [comment]
Looks good to me.
