### ISSUE TITLE
Add figure of the workflow to the manuscript

### ISSUE THREAD

**Issue by wincowgerDEV** [U-Alberta/ADaPT-ML#6]
The current form of the manuscript is only words with no visuals. I think a person who stumbles upon the manuscript only might not be enticed to go to your github page without some visuals to help them get a sense of what they will get or learn there in the manuscript. One really good way of doing that is with a visual. I like the main visual that you have on your paper.md file that shows the workflow. Perhaps that or something similar could be included in the manuscript?

**Comment by nulberry** [comment]
This is a great idea, thank you. I have included the main system diagram with a short caption in the newest version of the manuscript (1dd2aaae11c68fd637edcfad8568df75b235b7bd). I made it 70% of the size it could be, so please let me know if you have further suggestions on how to make it easy to read or on its position within the document.

**Comment by wincowgerDEV** [comment]
I like the size and positioning, thanks for adding the figure in, I think it will help folks more rapidly understand all the cool stuff your application does.
